language: python

python:
  - "3.7"

cache:
  - pip

matrix:
  fast_finish: true

sudo: required
dist: bionic

install:
  - sudo apt-get update
  # Xvfb / window manager
  - sudo apt-get install -y xvfb herbstluftwm

jobs:
  include:
    - name: lints
      install: pip install -r requirements.txt
      script: 
        - pylint nutrition --max-line-length=120 --extension-pkg-whitelist=PySide2 --disable=fixme; exit $(($? & 3))
        - mypy nutrition --ignore-missing-imports
    - name: tests
      install: pip install -r requirements.txt
      before_script:
        - (herbstluftwm )&
        - sleep 1
      script: python -m unittest
