language: python

python:
  - "3.7"

cache:
  - pip

matrix:
  fast_finish: true

sudo: required
dist: bionic

env:
  - QT_QPA_PLATFORM="offscreen"

jobs:
  include:
    - name: lints
      install: pip install -r requirements.txt
      script: 
        - pylint nutrition --max-line-length=120 --extension-pkg-whitelist=PySide2 --disable=fixme; exit $(($? & 3))
        - mypy nutrition --ignore-missing-imports
    - name: tests
      install: pip install -r requirements.txt
      script: xvfb-run python -m unittest
