language: python

python:
  - "3.7"

matrix:
  fast_finish: true

sudo: required
dist: bionic
services:
  - xvfb

jobs:
  include:
    - name: lints
      install: pip install -r requirements.txt
      script: 
        - pylint nutrition --max-line-length=120 --extension-pkg-whitelist=PySide2 --disable=fixme; exit $(($? & 3))
        - mypy nutrition --ignore-missing-imports
    - name: tests
      install: pip install -r requirements.txt
      # Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
      before_script:
        - "export DISPLAY=:99.0"
      script: python -m unittest
